### ISSUE TITLE
Where and how to get an API token for the AI keyword generation?

### ISSUE THREAD

**Issue by AndisGrossteins** [joincodeconda/generate-photo-metadata-csv#1]
There should be some guidance on how to obtain the API token for use in the script in README.md.

A quick read through the script seems to indicate it's sending original full-resolution images to a third party service.
For one, modern cameras generate huge images (30 - 60 megapixels) and it would be better to scale down to 1000×1000px and send resized images.
Then, some people might have privacy and copyright concerns. That also should be mentioned in the README.md.

**Comment by marks909** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WR240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by AndisGrossteins** [comment]
Did you read the issue report or just the title?
I'm alsoe a software developer and know what GitHub issues are used for.

**Comment by joincodeconda** [comment]
Take a look at PhotoTag.ai's Lightroom Plug-in (launched after this script was developed). It may better suit your needs: https://www.phototag.ai/lightroom-plugin
